### PR TITLE
Set ambient light to avoid exactly black shadow.

### PR DESCRIPTION
**Pull request by fidergo-stephane-gourichon**
Makes limit between sphere and floor much clearer and cleaner.

### CODE REVIEW

**Comment by fidergo-stephane-gourichon** [comment]
This is best appreciated after merging #4 #5 #6 and #7.

The viewer might be surprised that the shadow extends beyond the lower bound of the image. As far as I know, this is actually accurate given the geometry of the scene. "Fixing" this would imply to push the sphere further and reduce the angular width of view.

with_shadow_and_PR_4_5_6_7

**Comment by fidergo-stephane-gourichon** [comment]
Pushed branch that already combines #4 #5 #6 #7, to avoid conflict of standalone #7 when merging on top of the others.
This branch now represents all changes combined.

You can still access standalone change as https://github.com/64/cmake-raytracer/pull/7/commits/381ebe2fa6a87290ba319b5d345a79aadca2ffba .

**Comment by fidergo-stephane-gourichon** [comment]
Here's result of latest push, compared with original:
with_shadow_and_PR_4_5_6_7_01
original image

**Comment by 64** [comment]
> Pushed branch that already combines #4 #5 #6 #7, to avoid conflict of standalone #7 when merging on top of the others. This branch now represents all changes combined.

Sorry, only noticed this after merging the others.

This is great work - thanks so much. My only concern, as you said, is that it's a bit surprising to the viewer, and for a project like this I'd rather have an image that's not surprising over something that's more physically accurate. I think it can be faked to look nicer by simply not painting the shadow when the depth is >= 2 (so we don't see it in the reflection of the sphere). I'll do this now and merge everything together.

**Comment by fidergo-stephane-gourichon** [comment]
Thanks for merging the PRs.

> This is great work - thanks so much. My only concern, as you said, is that it's a bit surprising to the viewer, and for a project like this I'd rather have an image that's not surprising over something that's more physically accurate. 

Well, you're not selling a Hollywood movie, it's a hacker project. So, if the viewer is surprised then educated and makes an actual progress, that's the option I would prefer. 

> I think it can be faked to look nicer by simply not painting the shadow when the depth is >= 2 (so we don't see it in the reflection of the sphere). I'll do this now and merge everything together.

I saw you implemented it. I saw the result and think it looks like a bug, making the program appear less capable than it actually is.

But hey, it's your project and if I disagree I can fork it and launch my own blender competitor. ;-)

**Pull request merged**
